name: 'Code Quality'

on:
    pull_request:
    push:

env:
    PHP_VERSION: 8.0

jobs:
    phpstan:
        name: 'PHPStan'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/cache@v3
                with:
                    path: /tmp/composer-cache
                    key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
            -   uses: php-actions/composer@v6
                with:
                    php-version: ${{ env.PHP_VERSION }}

            -   name: 'PHPStan Static Analysis'
                uses: php-actions/phpstan@v3
                with:
                    configuration: phpstan.neon.dist
                    memory_limit: 128M
